INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (1, 1, 1,N'Parches de ojos' ,10,15)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (2, 2, 2,N'Delineador' ,1,70)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (3, 3, 3,N'Labial Maybeline Rojo' ,2,80)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (4, 4, 4,N'Labial Maybeline Rosa' ,1,80)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (5, 5, 5,N'Labial Maybeline Negro' ,3,80)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (6, 6, 6,N'Macarilla facial de coco' ,5,30)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (7, 7, 7,N'Mascarilla Facial para puntos  negros' ,4,15)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (8, 8, 8,N'Mascar de pestañas' ,7,50)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (9, 9, 9,N'crema de cejas' ,1,60)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (10, 10, 10,N'Mascarilla facial de aguacate' ,10,25)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (11, 11, 11,N'Paleta de sombras Marshall' ,1,200)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (12, 12, 12,N'Set de contouring' ,1,180)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (13, 13, 13,N'Set de brochas' ,3,250)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (14, 14, 14,N'Losion facial antiarrugas' ,1,100)
INSERT [dbo].[Detalle_Factura] ([Id_detalle_factura], [Id_Factura], [Id_Producto], [Descripcion],[Cantidad],[Precio_Venta]) VALUES (15, 15, 15,N'Polvo sellador traslucido' ,2,30)

